### ISSUE TITLE
project build fail

### ISSUE THREAD

**Issue by HQTracy** [caobaokang419/WeatherApp#1]
How to solve this problem?????  thanks !!

F:\Work_Github\Func\WeatherApp-master\app\src\main\java\com\gary\weatherdemo\ui\ItemView\CurWeatherViewItem.java:10: 错误: 程序包com.gary.weatherdemo.databinding不存在
import com.gary.weatherdemo.databinding.CurWeatherBinding;
                                       ^
F:\Work_Github\Func\WeatherApp-master\app\src\main\java\com\gary\weatherdemo\ui\ItemView\CurWeatherViewItem.java:17: 错误: 找不到符号
    private CurWeatherBinding mDataBinding;
            ^
  符号:   类 CurWeatherBinding
  位置: 类 CurWeatherViewItem
F:\Work_Github\Func\WeatherApp-master\app\src\main\java\com\gary\weatherdemo\ui\ItemView\ForecastDayViewItem.java:9: 错误: 程序包com.gary.weatherdemo.databinding不存在
import com.gary.weatherdemo.databinding.WeatherForecastDayBinding;
                                       ^
F:\Work_Github\Func\WeatherApp-master\app\src\main\java\com\gary\weatherdemo\ui\ItemView\ForecastDayViewItem.java:17: 错误: 找不到符号
    private WeatherForecastDayBinding mDataBinding;
            ^
  符号:   类 WeatherForecastDayBinding
  位置: 类 ForecastDayViewItem
F:\Work_Github\Func\WeatherApp-master\app\src\main\java\com\gary\weatherdemo\room\weather\CityForecastDAO.java:20: 错误: There is a problem with the query: [SQLITE_ERROR] SQL error or missing database (no such column: id)
    List<CityForecastEntity> getAllByIds(long[] ids);
                             ^
F:\Work_Github\Func\WeatherApp-master\app\src\main\java\com\gary\weatherdemo\room\city\CityBeanDAO.java:23: 错误: There is a problem with the query: [SQLITE_ERROR] SQL error or missing database (no such column: id)
    List<CityBeanEntity> getAllByIds(long[] ids);
                         ^
6 个错误
:app:compileDebugJavaWithJavac FAILED

**Comment by caobaokang419** [comment]
These compile issues have been fixed now,please download the newest version.

**Comment by HQTracy** [comment]
Thank you very much,it can be compiled normally
